//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;

public abstract class FileSystemElement
{
	protected string name_;
    protected long size_;
    private DateTime creation_date_;
    private DirectoryInfo parent_;

    public DateTime CreationDate
    {
        get
        {
            return creation_date_;
        }
        set
        {
            //TODO: Check valid value
            creation_date_ = value;
        }
    }

    public DirectoryInfo Parent
    {
        get
        {
            return parent_;
        }
        set
        {
            //TODO: Check valid value
            parent_ = value;
        }
    }

    public string Name
	{
        get
        {
            return name_;
        }
        set
        {
            //TODO: Check valid value
            name_ = value;
        }
	}

    public long Size
    {
        get
        {
            return size_;
        }
        set
        {
            //TODO: Check valid value
            size_ = value;
        }
    }

	public virtual void Read()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CheckName()
	{
		throw new System.NotImplementedException();
	}
}

