//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;

namespace file_manager_modelLib.Model
{
    public abstract class FileSystemElement : IMyFileSystemInfo
    {
        protected string _name;
        protected string _extension;
        protected string _path;
        protected DateTime _lastAccessTime;
        protected DateTime _lastWriteTime;
        protected DateTime _creationTime;

        public string GetName()
        {
            return this._name;
        }

        public string GetPath()
        {
            return this._path;
        }

        public string GetExtension()
        {
            return this._extension;
        }

        public DateTime GetLastAccessTime()
        {
            return this._lastAccessTime;
        }

        public DateTime GetLastWriteTime()
        {
            return this._lastWriteTime;
        }

        public DateTime GetCreationTime()
        {
            return this._creationTime;
        }

        public MyDirectory GetParent();
    }
}

