//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;

namespace file_manager_modelLib.Model
{
    public class MyDirectory : FileSystemElement
    {
        public MyDirectory(string name, string extension, string path, 
            DateTime creationTime, DateTime lastAccessTime, DateTime lastWriteTime)
        {
            this._name = name;
            this._extension = extension;
            this._path = path;
            this._lastAccessTime = lastAccessTime;
            this._lastWriteTime = lastWriteTime;
            this._creationTime = creationTime;
        }
    }
}

