//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MyDirectory : FileSystemElement, ICompositeElement, IEditedElement
{
    public MyDirectory(string name)
    {
        this.name_ = name;
    }

    public virtual void IEditedElement.Delete()
	{
		throw new System.NotImplementedException();
	}

	public override void Read()
	{
		throw new System.NotImplementedException();
	}
}

