//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;

namespace file_manager_modelLib.Model
{
    public class MyDrive : IMyDriveInfo, IMyDriveOperations
    {
        private string _label;
        private DriveType _type;
        private string _format;
        private long _freeSpace;
        private long _size;

        public string Label
        {
            get
            {
                return _label;
            }
            set
            {
                //TODO: Check valid value
                _label = value;
            }
        }

        public DriveType Type
        {
            get
            {
                return _type;
            }
            set
            {
                //TODO: Check valid value
                _type = value;
            }
        }

        public string Format
        {
            get
            {
                return _format;
            }
            set
            {
                //TODO: Check valid value
                _format = value;
            }
        }

        public long FreeSpace
        {
            get
            {
                return _freeSpace;
            }
            set
            {
                //TODO: Check valid value
                _freeSpace = value;
            }
        }

        public long Size
        {
            get
            {
                return _size;
            }
            set
            {
                //TODO: Check valid value
                _size = value;
            }
        }

        public MyDrive(string name)
        {
            this.name_ = name;
        }
    }
}

