//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;

public class MyDrive : FileSystemElement, ICompositeElement
{
    private string label_;
    private DriveType type_;
    private string format_;
    private long free_space_;
    private string p;

    public string Label
    {
        get
        {
            return label_;
        }
        set
        {
            //TODO: Check valid value
            label_ = value;
        }
    }

    public DriveType Type
    {
        get
        {
            return type_;
        }
        set
        {
            //TODO: Check valid value
            type_ = value;
        }
    }

    public string Format
    {
        get
        {
            return format_;
        }
        set
        {
            //TODO: Check valid value
            format_ = value;
        }
    }

    public long FreeSpace
    {
        get
        {
            return free_space_;
        }
        set
        {
            //TODO: Check valid value
            free_space_ = value;
        }
    }

    public MyDrive(string name)
    {
        this.name_ = name;
    }
    
    private object children_list_
	{
		get;
		set;
	}

	public override void Read()
	{
		throw new System.NotImplementedException();
	}

    public override void ICompositeElement.GetChildrenList()
	{
		throw new System.NotImplementedException();
	}

}

