//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;

public class MyFile : FileSystemElement, IEditedElement
{
	private string extention_;

    public string Extension
    {
        get
        {
            return extention_;
        }
        set
        {
            //TODO: Check valid value
            extention_ = value;
        }
    }

    public MyFile(string name)
    {
        name_ = name_;
    }

	public virtual void CheckExtention()
	{
		throw new System.NotImplementedException();
	}

    public virtual void IEditedElement.Delete()
	{
		throw new System.NotImplementedException();
	}

	public override void Read()
	{
		throw new System.NotImplementedException();
	}

	protected virtual void IsSupported()
	{
		throw new System.NotImplementedException();
	}
}

