//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;

namespace file_manager_modelLib.Model
{
    public class MyFile : FileSystemElement
    {
        protected long _size;

        public MyFile(string name, long size, string extension, string path, 
            DateTime creationTime, DateTime lastAccessTime, DateTime lastWriteTime)
        {
            this._name = name;
            this._size = size;
            this._extension = extension;
            this._path = path;
            this._lastAccessTime = lastAccessTime;
            this._lastWriteTime = lastWriteTime;
            this._creationTime = creationTime;
        }

        public void IMyFileSystemOperations.Delete();

        public void IMyFileSystemOperations.Exists();

        public void IMyFileSystemOperations.MoveTo(string destDirName);

        public void IMyFileSystemOperations.Read();

        public void IMyFileSystemOperations.Create();

        public long Size
        {
            get
            {
                return _size;
            }
        }
    }
}


