//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace file_manager_modelLib.Model
{
    public class TxtFile : MyFile
    {
        public override void Read();

        public void GetWordFrequency();

        public void SearchInFile();

        public void Edit();
    }
}

