//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TxtFile : MyFile
{
	public override void Read()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetWordFrequency(int word_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SearchInFile(string query)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Edit(string text)
	{
		throw new System.NotImplementedException();
	}

}

