//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MyDrive : FileSystemElement, ICompositeElement
{
	private object children_list_
	{
		get;
		set;
	}

	public override void Read()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Format()
	{
		throw new System.NotImplementedException();
	}

    public override void ICompositeElement.GetChildrenList()
	{
		throw new System.NotImplementedException();
	}

}

