//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MyFile : FileSystemElement, IEditedElement
{
	private object extention_
	{
		get;
		set;
	}

	private object date_
	{
		get;
		set;
	}

    public virtual void IEditedElement.SetName(String name)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CheckExtention()
	{
		throw new System.NotImplementedException();
	}

    public virtual void IEditedElement.Delete()
	{
		throw new System.NotImplementedException();
	}

	public override void Read()
	{
		throw new System.NotImplementedException();
	}

	protected virtual void IsSupported()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetExtention()
	{
		throw new System.NotImplementedException();
	}

}

