//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FileSystemController
{
    private ListColumn left_column;
    private ListColumn right_column;

	public virtual void Select(int[] elements_list)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Copy(string destination)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Move(string destination)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Read()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateNewFile(string name)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateNewFolder(string name)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Merge()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Rename(string new_name)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Search(string query)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SpecialMegre()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ClearSelection()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Edit()
	{
		throw new System.NotImplementedException();
	}

	private void IsCopyAllowed()
	{
		throw new System.NotImplementedException();
	}

	private void SetActiveElement(int id)
	{
		throw new System.NotImplementedException();
	}

	private void IsDeleteAllowed()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SortByDate()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SortByExtention()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SortByName()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SortBySize()
	{
		throw new System.NotImplementedException();
	}

}

