//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;

namespace file_manager_test_app
{
    //Based on "mediator" pattern
    public class FileSystemController
    {
        private Column _leftColumn;
        private Column _rightColumn;
        private Column _activeColumn;

        public FileSystemController()
        {
            _leftColumn = new Column();
            _rightColumn = new Column();
            _activeColumn = _leftColumn;
        }

        public void SetActiveColumn(int id)
        {
            if (id == 0) 
            {
                _activeColumn = _leftColumn;
            }
            else if (id == 1) 
            {
                _activeColumn = _rightColumn;
            }
        }

        public int GetActiveColumnId()
        {
            return (_activeColumn.Equals(_leftColumn) ? 0 : 1);
        }

        public void Select(int[] elements)
        {
            if (elements.Length > 0)
            {
                _activeColumn.Select(elements);
            }
        }

        public void CopyTo(string destination)
        {
            _activeColumn.CopySelectedElementsTo(destination);
        }

        public void SetActive(int id)
        {
            _activeColumn.ActiveElement = id;
        }

        public void Delete()
        {
            _activeColumn.DeleteSelectedElements();
        }

        public void MoveTo(string destination)
        {
            _activeColumn.MoveSelectedElementsTo(destination);
        }

        public void Read()
        {
            throw new System.NotImplementedException();
        }

        public void CreateNewTxtFile(string name)
        {
            _activeColumn.CreateNewTxtFile(name);
        }

        public void CreateNewDirectory(string name)
        {
            _activeColumn.CreateNewDirectory(name);
        }

        public void Merge()
        {
            throw new System.NotImplementedException();
        }

        public void Rename(string name)
        {
            _activeColumn.RenameActiveElement(name);
        }

        public void Search(string query)
        {
            throw new System.NotImplementedException();
        }

        public void SpecialMegre()
        {
            throw new System.NotImplementedException();
        }

        public void ClearSelection()
        {
            _activeColumn.ClearSelection();
        }

        public void Edit()
        {
            throw new System.NotImplementedException();
        }

        private void IsCopyAllowed()
        {
            throw new System.NotImplementedException();
        }

        private void SetActiveElement(int id)
        {
            throw new System.NotImplementedException();
        }

        private void IsDeleteAllowed()
        {
            throw new System.NotImplementedException();
        }

        public void SortByDate()
        {
            throw new System.NotImplementedException();
        }

        public void SortByExtention()
        {
            throw new System.NotImplementedException();
        }

        public void SortByName()
        {
            throw new System.NotImplementedException();
        }

        public void SortBySize()
        {
            throw new System.NotImplementedException();
        }

    }
}

